image: ubuntu:disco

variables:
  REPO: "554546661178.dkr.ecr.eu-central-1.amazonaws.com/rust-musl"

stages:
  - build

before_script:
  - apt-get update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y docker.io

build:
  stage: build
  script:
    - export TAG=$(date +%Y-%m-%d)
    - /etc/init.d/docker start
    - docker build -t $REPO:$TAG .
    - docker tag $REPO:$TAG $REPO:latest
        --buid-arg TOOLCHAIN=nightly
