image: ubuntu:focal

services:
  - 554546661178.dkr.ecr.eu-central-1.amazonaws.com/docker:stable-dind-2

variables:
  REPO: "554546661178.dkr.ecr.eu-central-1.amazonaws.com/rust-musl"
  DEBIAN_FRONTEND: noninteractive
  TOOLCHAIN: nightly-2020-09-20
  OPENSSL_VERSION: "1.0.2t"
  POSTGRESQL_VERSION: "11.4"
  DOCKER_HOST: tcp://localhost:2375

# docker build --build-arg TOOLCHAIN=nightly-2019-11-01 --build-arg POSTGRESQL_VERSION=$POSTGRESQL_VERSION -t $REPO:$TAG .

stages:
  - build

before_script:
  - apt-get update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y docker.io awscli

build:
  stage: build
  script:
    - export TAG=$(date +%Y-%m-%d)
    - docker build --build-arg TOOLCHAIN=$TOOLCHAIN --build-arg POSTGRESQL_VERSION=$POSTGRESQL_VERSION -t $REPO:$TAG .
    - docker tag $REPO:$TAG $REPO:latest
    - docker history $REPO:$TAG
    - aws ecr get-login --region=eu-central-1 | awk '{gsub(/ -e none/, ""); print}' | sh
    - docker push $REPO:$TAG
    - docker push $REPO:latest
