image: ubuntu:focal

services:
  - 554546661178.dkr.ecr.eu-central-1.amazonaws.com/docker:stable-dind-2

variables:
  REPO: "554546661178.dkr.ecr.eu-central-1.amazonaws.com/rust-musl"
  DEBIAN_FRONTEND: noninteractive
  OPENSSL_VERSION: "1.0.2t"
  POSTGRESQL_VERSION: "11.4"
  DOCKER_HOST: tcp://localhost:2375

stages:
  - build

before_script:
  - apt-get update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y docker.io awscli

.build_template: &build_definition
  stage: build
  script:
    - docker build --build-arg TOOLCHAIN=$TOOLCHAIN --build-arg POSTGRESQL_VERSION=$POSTGRESQL_VERSION -t $REPO:$TOOLCHAIN .
    - docker history $REPO:$TOOLCHAIN
    - aws ecr get-login --region=eu-central-1 | awk '{gsub(/ -e none/, ""); print}' | sh
    - docker push $REPO:$TOOLCHAIN


build_nightly:
  <<: *build_definition
  variables:
    TOOLCHAIN: nightly-2020-09-20

build_stable:
  <<: *build_definition
  variables:
    TOOLCHAIN: 1.45.0