image: ubuntu:disco

variables:
  REPO: "554546661178.dkr.ecr.eu-central-1.amazonaws.com/rust-musl"
  DEBIAN_FRONTEND: noninteractive

stages:
  - build

before_script:
  - apt-get update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y docker.io awscli

build:
  stage: build
  script:
    - export TAG=$(date +%Y-%m-%d)
    - /etc/init.d/docker start; sleep 3
    - docker build --build-arg TOOLCHAIN=nightly -t $REPO:$TAG .
    - docker tag $REPO:$TAG $REPO:latest
    - docker history $REPO:$TAG
    - aws ecr get-login --region=eu-central-1 | awk '{gsub(/ -e none/, ""); print}' | sh
    - docker push $REPO:$TAG
    - docker push $REPO:latest
